services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myapp.wsgi"
    postDeployCommand: "python manage.py migrate"
