# Generated by Django 4.2.7 on 2024-01-25 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebarquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssgi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='ssgi',
            name='folder',
            field=models.CharField(default=None),
        ),
    ]
