# Generated by Django 4.2.7 on 2024-01-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebarquery', '0002_alter_ssgi_date_alter_ssgi_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssgi',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
